workflows:
  android-native-build:
    name: Android Native Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17  # Java version required by Gradle
    working_directory: android  # Keep it inside the android folder
    scripts:
      - name: Set Gradle Permissions
        script: chmod +x ./gradlew  # Ensure the Gradle wrapper is executable
      - name: Build Android APK
        script: ./gradlew assembleRelease  # Build the release APK
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
